In [6]:
# initially we will wrk with dataset where we will use 
# Classification - output- 2 categories - Binary classification 
# my output something like yes / no
# 900 yes and 100 yes with 1000 dataset 
# 9000:100 = 9;1 this is known as imbalanced datset 
# this type of imbalanced dataset will create a problem while we solving the problem of machine learning 
# the model that we creating which is responisble for predicting will get biased towards the maximum number of data
# so it is necessary to fix the imbalanced datset and we try to make syre thar both this data points becone equal.
# for this we will use 2 techniques 
# 1. UP sampling 2. Down Sampling 
# in up sampling we will increase the number of data points from 100 which is basically minority 
# in downsampling we will reduce the datapoints from here which is majority

### Handling Imbalanced Dataset 
1.Up sampling 

2. Down Sampling

In [10]:
import numpy as np 
import pandas as pd 

# set the random seed for reproducibility 
np.random.seed(123)

# Create a Dataframe with 2 classes 
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [11]:
n_class_0,n_class_1

(900, 100)

In [20]:
### Creating my Dataframe with imbalanced dataset
class_0 = pd.DataFrame({
    'feature_1':np.random.normal(loc=0,scale=1,size=n_class_0),
    'feature_2':np.random.normal(loc=0,scale=1,size=n_class_0),
    'target':[0] *n_class_0
})
class_1 = pd.DataFrame({
    'feature_1':np.random.normal(loc=0,scale=1,size=n_class_1),
    'feature_2':np.random.normal(loc=0,scale=1,size=n_class_1),
    'target':[1] *n_class_1
})

In [23]:
df = pd.concat([class_0,class_1]).reset_index(drop=True)

In [24]:
df.head()

   feature_1  feature_2  target
0  -0.471276   0.328462       0
1   1.084072   1.038230       0
2  -0.379223   1.147064       0
3  -0.362274   0.638254       0
4  -0.681071  -1.075766       0

In [25]:
df.tail()

     feature_1  feature_2  target
995   0.720690  -0.021511       1
996  -0.050922   1.709793       1
997   0.709784   1.324917       1
998  -0.182311  -0.450763       1
999   0.838910   0.240773       1

In [26]:
print(df['target'].value_counts())

target
0    900
1    100
Name: count, dtype: int64

In [30]:
## Up sampling 
df_minority=df[df['target'] == 1]
df_majority=df[df['target'] == 0]

In [38]:
# here it basically creates and it extrapolates the point 
from sklearn.utils import resample 
df_minority_upsampled = resample(df_minority,replace=True,
        n_samples=len(df_majority),
        random_state=42) # Sample with replacement

In [40]:
df_minority_upsampled.shape ## this mean here i created more data points over here and all the dataset is basically giving 
# the output as 1.

(900, 3)

In [41]:
df_minority_upsampled.head() # confirmatory purpose

     feature_1  feature_2  target
951   0.701255  -1.943519       1
992   0.322342   1.289170       1
914   0.500618  -0.661830       1
971  -0.077056   0.907951       1
960  -1.369782  -1.017595       1

In [45]:
df_upsampled = pd.concat([df_majority,df_minority_upsampled])

In [46]:
df_upsampled['target'].value_counts() # from this we can see  that we increased the datapoints

target
0    900
1    900
Name: count, dtype: int64

### for Down sampling

In [48]:
import numpy as np 
import pandas as pd 

# set the random seed for reproducibility 
np.random.seed(123)

# Create a Dataframe with 2 classes 
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

n_class_0,n_class_1

### Creating my Dataframe with imbalanced dataset
class_0 = pd.DataFrame({
    'feature_1':np.random.normal(loc=0,scale=1,size=n_class_0),
    'feature_2':np.random.normal(loc=0,scale=1,size=n_class_0),
    'target':[0] *n_class_0
})
class_1 = pd.DataFrame({
    'feature_1':np.random.normal(loc=0,scale=1,size=n_class_1),
    'feature_2':np.random.normal(loc=0,scale=1,size=n_class_1),
    'target':[1] *n_class_1
})

df = pd.concat([class_0,class_1]).reset_index(drop=True)

print(df['target'].value_counts())

target
0    900
1    100
Name: count, dtype: int64

In [49]:
## Downsampling 
df_minority=df[df['target'] == 1]
df_majority=df[df['target'] == 0]

In [54]:
# here it basically creates and it extrapolates the point 
from sklearn.utils import resample 
df_majority_downsampled = resample(df_majority,replace=False,
        n_samples=len(df_minority),
        random_state=42) # Sample with replacement

In [55]:
df_majority_downsampled.shape

(100, 3)

In [56]:
df_downsampled = pd.concat([df_minority,df_majority_downsampled])

In [58]:
df_downsampled.target.value_counts()
# here downsampling is bad because here we are loosing our data points

target
1    100
0    100
Name: count, dtype: int64

In [60]:
## from this we can conclude that we can probably do up smapling and probably to 
# try to solve thus particular problem whenever we are trying to train our model.

In [62]:
## here this techniques is not that good because my data is still in that position like for ecample take a graph 
# where 900 dtaa pointas are red colour and 100 datapoints are in blue 
# so by using upsampling method we are increasing the blue datapoints by adding the datapoints just above it ..
# so here due to nearly that position , the variance is not increasing at all..
# so in order to increase the variance , we can specifically do .. we can use a interpolating techniques 
# interpolating basically means we are creating our own synthetic data.
3